name: Secrets example
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          if [ "$USER" == "naor0003@gmail.com" ]
          then
            echo "Got secret user"
          fi
          if [ "$PASS" == "Osnat1308" ]
          then
            echo "Got secret pass"
          fi
        env: 
          USER: ${{ secrets.USER }}
          PASS: ${{ secrets.PASS }}